#ifndef _FEATURES_H_
#define _FEATURES_H_

#define FEATURE_NOSRCADDR		(1ULL<<0)

#define FEATURE_MSG_AUTH			(1ULL<<1)

#define FEATURE_MSGR_KEEPALIVE2	(1ULL<<2)

#define FEATURE_RECONNECT_SEQ	(1ULL<<3)

#define FEATURES_ALL \
	(FEATURE_NOSRCADDR | \
	FEATURE_MSG_AUTH | \
	FEATURE_MSGR_KEEPALIVE2 | \
	FEATURE_RECONNECT_SEQ)


#endif
